### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by NevilleS**
Because all good projects need a logo

### CODE REVIEW

**Comment by jasonrhodes** [comment]
+1

**Comment by nickhudkins** [comment]
While I appreciate your contribution, we only accept contributions begrudgingly after 100s of people post :+1: as a comment, day after day, and several angry medium posts are created.

**Comment by beardyman** [comment]
https://s-media-cache-ak0.pinimg.com/236x/82/03/55/82035550dcd87f533fe8d905e47146fc.jpg

**Comment by NevilleS** [comment]
Gotcha - I've got a patch on my fork that works for me, hopefully if this PR helps others in the future I can make whatever changes needed so this can land 👍

**Comment by NevilleS** [comment]
Updated to latest master 👍

**Comment by nickhudkins** [comment]
I am gonna need at least 3-5 more commits adjusting code style so that I can request that you squash them and rebase.

**Comment by nickhudkins** [comment]
A beautiful mess.

**Pull request merged**
